services:
  traefik:
    image: traefik:3
    restart: always
    ports:
        - "80:80/tcp" # HTTP
        - "443:443/tcp" # HTTPS
        - "8883:8883/tcp" # MQTTS
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik"
      - "--providers.file.watch=true"
      
      # HTTP
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      
      # HTTPS
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.middlewares=security-headers@file"

      # MQTTS
      - "--entrypoints.mqtt-tcp.address=:8883/tcp"

      - "--certificatesresolvers.httpresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.httpresolver.acme.caserver=${ACME_CASERVER}"
      - "--certificatesresolvers.httpresolver.acme.eab.kid=${ACME_EAB_KID}"
      - "--certificatesresolvers.httpresolver.acme.eab.hmacencoded=${ACME_EAB_HMACENCODED}"
      - "--certificatesresolvers.httpresolver.acme.storage=/acme/acme.json"
      - "--certificatesresolvers.httpresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.httpresolver.acme.httpchallenge.entrypoint=web"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme:/acme
      - ./services/traefik/dynamic.yaml:/etc/traefik/dynamic.yaml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${PROJECT_BASE_URL}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.options=default"
      - "traefik.http.routers.traefik.tls.certresolver=httpresolver"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_USER}:${TRAEFIK_HTPASSWD}"

      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
   
  db:
    image: postgres:15-alpine
    container_name: farmspt_postgres
    restart: always
    environment:
      POSTGRES_DB: farmspt_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    restart: always
    container_name: farmspt_keycloak
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://db:5432/farmspt_db"
      KC_DB_USERNAME: "postgres"
      KC_DB_PASSWORD: "postgres"
      KC_PROXY_HEADERS: "xforwarded"
      KC_HOSTNAME: "keycloak.${PROJECT_BASE_URL}"
      KC_HOSTNAME_URL: "https://keycloak.${PROJECT_BASE_URL}"
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    expose:
      - "8080"
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.${PROJECT_BASE_URL}`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.routers.keycloak.tls.options=default"
      - "traefik.http.routers.keycloak.tls.certresolver=httpresolver"
    
      - "traefik.http.middlewares.keycloak-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.keycloak-headers.headers.customrequestheaders.X-Forwarded-Host=keycloak.${PROJECT_BASE_URL}"
      - "traefik.http.routers.keycloak.middlewares=keycloak-headers"

      - "traefik.http.routers.keycloak.service=keycloak"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - ./FarmSPT_Backend:/app  
    container_name: farmspt_backend
    restart: always
    expose:
      - "8000"
    environment:
      DEBUG: "True"
      DJANGO_SETTINGS_MODULE: "API.settings"
      DB_NAME: "farmspt_db"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_HOST: "db"
      DB_PORT: 5432
      KEYCLOAK_URL: "https://keycloak.${PROJECT_BASE_URL}"
      KEYCLOAK_REALM: "FarmSPT_v1"
      KEYCLOAK_CLIENT_ID: "farmspt_v1-api"
      KEYCLOAK_CLIENT_SECRET: "${KEYCLOAK_CLIENT_SECRET}"
    depends_on:
       db:
        condition: service_healthy
       keycloak:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.${PROJECT_BASE_URL}`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.options=default"
      - "traefik.http.routers.backend.tls.certresolver=httpresolver"

      - "traefik.http.routers.backend.service=backend"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  mqtt:
    build:
      context: ./FarmSPT_MQTT
    restart: always
    container_name: farmspt_mqtt
    environment:
      DEBUG: "True"
      OAUTH_JWT_KEY: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA05N8IfsW+GSJ26Z+nZU+ayU4e5hFSVZHMFTXgzPDd709e3BzdCtbfHY/nfSExD2xzkRzZoC0SdTAhjskg2r3LGqtJuuMjrmhYldVh3fRX1Oyo8nQum+t9oxGWJGodeZXBb9cKvktgKaQi2tmmNe2vVQSX1yEBwIPPO14YE+4dV+fVKjqJKvvlhUuExpF3IaTdlUbr2EsV3irN3xYIcaUlsVNLDHPgG8TZJZy0A/1qXV4xHJhIMuc8APHnaOTjIkJKRx13jQLHAzYTSkZJvi6AXc1slHN2kx/dqZd3gI3MDMZMc+I+P8aCnFsj981SsOqY8mxj7BvDCzmDZS9yT4bCwIDAQAB"
      OAUTH_JWT_VALIDATE_EXP: "False"
      OAUTH_TOKEN_URL: "https://keycloak.${PROJECT_BASE_URL}/realms/FarmSPT_v1/protocol/openid-connect/token"
      KEYCLOAK_CLIENT_ID: "mqtt-api"
      KEYCLOAK_CLIENT_SECRET: "ENj82GqnPkMfG3DE5FUN6YnffK9N48bh"
    expose:
      - "8883"
    depends_on:
       db:
        condition: service_healthy
       keycloak:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.mqtt.rule=HostSNI(`mqtt.${PROJECT_BASE_URL}`)"
      - "traefik.tcp.routers.mqtt.entrypoints=mqtt-tcp"
      - "traefik.tcp.routers.mqtt.tls=true"
      - "traefik.tcp.routers.mqtt.tls.options=default"
      - "traefik.tcp.routers.mqtt.tls.certresolver=httpresolver"

      - "traefik.tcp.routers.mqtt.service=mqtt-tcp"
      - "traefik.tcp.services.mqtt-tcp.loadbalancer.server.port=8883"

      

volumes:
  postgres_data:
