pid_file /mosquitto/mosquitto.pid

listener 8883 0.0.0.0
allow_anonymous false
log_type all

# ***** TODO: Comment back in (does break anonymous auth, for testing only)  *****

plugin /usr/local/lib/mosquitto-oauth-plugin.so

plugin_opt_oauth_jwt_key MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA10azIRdzDaeVJgA/EoWswP8wc6byxdkbRtVWSPEs0hqcRBDLCBFZ5Bcos9kWLchzPpa9bI4ERoMIcawusMd5/gAw7Yy7D7eJSsgL3bqeTfmmsu6Ezkqv/M6FFw2QcLYOyLenO2+EF2qC/ZtmpBVLqgbCMvuEZQJsCClH6I1KWsRK29dfeG3BLkLStAG3lqIolo3g9keb8iPASH9TzHIzJsA3uSQHfr9z6Mq7iAkoNaivgwEPwLNLx/HwqqsF0cmHIPSKxjcmp9Urg5O1mllWxEIcADA5EioMa1meNOwYlW7FtExfpz+Qk5ZmqtHkeFB3rVy6QkH9cQTGjj29KdKgOwIDAQAB
plugin_opt_oauth_jwt_validate_exp false

plugin_opt_oauth_client_id mqtt-api
plugin_opt_oauth_client_secret ENj82GqnPkMfG3DE5FUN6YnffK9N48bh
plugin_opt_oauth_token_url https://keycloak.farmspt.ai.edvsz.hs-osnabrueck.de/realms/FarmSPT_v1/protocol/openid-connect/token



