pid_file /mosquitto/mosquitto.pid

listener 8883 0.0.0.0
allow_anonymous false
log_type all

# ***** TODO: Comment back in (does break anonymous auth, for testing only)  *****

plugin /usr/local/lib/mosquitto-oauth-plugin.so

plugin_opt_oauth_jwt_key MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA05N8IfsW+GSJ26Z+nZU+ayU4e5hFSVZHMFTXgzPDd709e3BzdCtbfHY/nfSExD2xzkRzZoC0SdTAhjskg2r3LGqtJuuMjrmhYldVh3fRX1Oyo8nQum+t9oxGWJGodeZXBb9cKvktgKaQi2tmmNe2vVQSX1yEBwIPPO14YE+4dV+fVKjqJKvvlhUuExpF3IaTdlUbr2EsV3irN3xYIcaUlsVNLDHPgG8TZJZy0A/1qXV4xHJhIMuc8APHnaOTjIkJKRx13jQLHAzYTSkZJvi6AXc1slHN2kx/dqZd3gI3MDMZMc+I+P8aCnFsj981SsOqY8mxj7BvDCzmDZS9yT4bCwIDAQAB
plugin_opt_oauth_jwt_validate_exp false

plugin_opt_oauth_client_id mqtt-api
plugin_opt_oauth_client_secret ENj82GqnPkMfG3DE5FUN6YnffK9N48bh
plugin_opt_oauth_token_url https://keycloak.farmspt.ai.edvsz.hs-osnabrueck.de/realms/FarmSPT_v1/protocol/openid-connect/token



