# Generated by Django 6.0.3 on 2026-06-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abtrace',
            name='syncpartners',
            field=models.ManyToManyField(blank=True, to='django_api.syncpartner'),
        ),
        migrations.AddField(
            model_name='fieldboundary',
            name='syncpartners',
            field=models.ManyToManyField(blank=True, to='django_api.syncpartner'),
        ),
    ]
