# Generated by Django 6.0.3 on 2026-06-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0002_abtrace_syncpartners_fieldboundary_syncpartners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abtrace',
            name='syncpartners',
            field=models.ManyToManyField(blank=True, null=True, to='django_api.syncpartner'),
        ),
        migrations.AlterField(
            model_name='fieldboundary',
            name='syncpartners',
            field=models.ManyToManyField(blank=True, null=True, to='django_api.syncpartner'),
        ),
    ]
